version: '3.7'
services:
  app:
    container_name: userwallet
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db-mysql
    env_file: ./.env
    networks:
      - appdb

  db-mysql:
    image: mysql:5.7
    container_name: db_mysql
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - appdb

volumes:
  api:
  database_mysql:

networks:
  appdb:
    driver: bridge

